### ISSUE TITLE
Every mode erroneously uses pentominoes

### ISSUE THREAD

**Issue by kdex** [shiromino/shiromino#1]
This issue has originally been reported by @gregorulm.

Currently, every mode uses pentominoes. This has likely happened in one of my commits where I moved macros into enum classes.

**Comment by kdex** [comment]
This was due to a slight oversight back [when I had originally introduced `GameType.h`](1c99c06). In that commit, I forgot to take the magic numbers along, which 417cdf2 fixes.

Eventually, this should be solved with `std::bitset`, but for now, that'll do.

**Comment by kdex** [comment]
@gregorulm: Please beware that 4a1c180 currently introduces a segfault when starting the game, so if you want to build it right now, you would have to drop that commit from the local git tree. @nightmareci is currently working on a bug fix for displays with refresh rates beyond 60 Hz and committed that work in 4a1c180.

We should probably use feature branches for WIP-status stuff in the future, such that building from `master` always works.

**Comment by gregorulm** [comment]
Thanks for addressing this issue so quickly! Using feature branches is a standard practice in software engineering for good reasons. I can only encourage you to adopt it for this project as well.

**Comment by kdex** [comment]
@gregorulm: Sure. It's just that I wasn't expecting people to use this repository so rapidly. The macOS build instructions, for example, weren't even up for 24 hours when I had received your initial support request. Rest assured that we'll put more work in improving our overall stability.

At the very least, the automated builds for Windows and macOS that I'm currently planning to output from our Continuous Integration pipeline should always work. For this process to be reliable though, we'd need unit tests. This is a pretty time-intensive endeavor, as there are currently no tests at all, and I'm also planning to transform the code base into standard C++ first. I'll document the general direction we're headed in a GitHub roadmap soon; just so that the process is more transparent.

In the meantime, @nightmareci has fixed the segfaults via 1690d6ae691f2f8783b37720bc1df9b3b241e08b. Thanks for being so patient; you should now be able to pull from `master`, and everything should just work.

**Comment by gregorulm** [comment]
@kdex My previous setup was to run Shiromino on a wine developer version (wine64) on macOS 10.15, so I was very eager to try out the native version. Anyway, I'm really happy to see increased development activity. I'll post a few issues/feature requests soon and contribute to the discussion a bit.
