### ISSUE TITLE
Game doesn't fully quit sometimes

### ISSUE THREAD

**Issue by kdex** [shiromino/shiromino#14]
There's a chance that closing the game window doesn't lead to the game process terminating; so if you ran shiromino from the command line, you have to send an additional SIGINT in order to quit.

**Comment by nightmareci** [comment]
@kdex I think I fixed this a while ago, when I found that occasionally the SDL2 quit event wouldn't be caught correctly (which is the event that's generated when you click the close button on a window). Now the code always catches every event up to and including the quit event or Alt+F4 being pressed, so I'm pretty confident the error won't show up anymore. Could you test closing the window several times on your system, to verify it's fixed now?

**Comment by kdex** [comment]
@nightmareci I've tested this on two different machines where I had previously been able to reproduce this behavior sometimes. Haven't been able to reproduce this anymore, so I'm assuming this is fixed now. Nice job!
