### ISSUE TITLE
Full-screen modes should not minimize when another screen gains focus

### ISSUE THREAD

**Issue by kdex** [shiromino/shiromino#17]
If you have the game running on monitor A and do something else on monitor B, every time monitor B receives focus, the game will minimize on monitor A, forcing you to maximize it when you want to return to your game.

**Comment by nightmareci** [comment]
I tried implementing this feature by just reading the SDL2 documentation and trying various functions that make the window shown when you switch to other windows on another monitor, but any function that makes the window shown also gives the game's window input focus, making it impossible to switch to another program while the fullscreen game window stays shown without input focus. [It appears there's no way to show a window and have the input focus go somewhere else currently with SDL2](https://stackoverflow.com/questions/25126617/sdl2-raising-a-window-without-giving-it-focus), so I'm closing this issue now. But if a future version of SDL2 allows this feature, we could add it then.
