### ISSUE TITLE
Make selected mode always obvious in screenshot

### ISSUE THREAD

**Issue by gregorulm** [shiromino/shiromino#32]
I sometimes take screenshots of my games. However, the G1 modes are ambiguous. Just from looking at a screenshot, it is not possible to determine if a game was played in G1 Master or G1 20g as both frames are grey. I therefore suggest modifying the frame for G1 20G. Gold would be a choice in line with the aesthetics of the game that inspired this mode, which turns the timer golden in 20G, Alternative, a text label could be added. My preference would be to use a unique color for the frame, though.

**Comment by FelicityVi** [comment]
Thank you for the suggestion. I've added a golden frame for G1 20G to address this ([`5a3a941`](https://github.com/shiromino/shiromino/commit/5a3a941061187aa0fad7c9493c7d25aee8f93d3a)).
