### ISSUE TITLE
Add 'infinite' practice session

### ISSUE THREAD

**Issue by gregorulm** [shiromino/shiromino#33]
One of the nicest features of  Texmaster is that it is possible to set a flag called `infinite` for practice. This allows you to set a starting point, e.g. G2 Master 900, but the level never increases, meaning that you can practice endurance. I suggest adding a similar flag to Shiromino. It would be great if there was also a separate level counter, i.e. freeze the regular level counter at the selected starting level, but have a separate counter that keeps track of how many levels you've survived (you may want to use a more generous limit, e.g. 9999 or 99999 or no limit at all).

You could modify the GUI like this:
- keep current level selector
- add a separate field to the right that flip between infinite on and off (default: off)

e.g. the user sees:
G2 Master  [900] [infinite]

Navigating between the mode (G1...G3) is done with `up`/`down`. You reach the selector via `right` and once the level is highlighted, you use `up`/`down` to make your choice. In order to move on to the field for the infinite option, you hit `right` again and use `up`/`down` to toggle this option.

**Comment by FelicityVi** [comment]
Though it is not as convenient as just picking a mode and level, speed timings can be set manually to whatever you like in the Multi-Editor now that it has been brought back, and the Multi-Editor is where we will ultimately keep any feature like this.

In the future, there will be buttons in the Multi-Editor to load speed timings from a specific mode/level, which would make it pretty close in terms of convenience.
