### ISSUE TITLE
Background erroneously flips to lv. 1000 image at lv. 999

### ISSUE THREAD

**Issue by gregorulm** [shiromino/shiromino#34]
In game modes that end at lv. 999, it sometimes happens that the background image for lv. 1000+ is shown at the very end. I can't reliably reproduce this bug, but I can provide screenshots if you want.

**Comment by gregorulm** [comment]
This might be somewhat more complicated but, which is obvious when watching replays with section timers as one of the following two happens:
- the background image doesn't flip to the lv. 1000 screen and the section time for 900-999 is not separately displayed
- the background image does flip to the lv. 1000 screen and the section time for 900-999 is displayed

The desired behavior is (probably) to not flip to the lv. 1000 background and show the lv. 900-999 section time. However, a good point could be made for having some kind of victory background that is shown when you hit 999 as I quite like the effect of having a different background image at the end of the game.

**Comment by gregorulm** [comment]
A screenshot is in #12. The picture of the clouds is for the 1000+ section.

**Comment by kdex** [comment]
@gregorulm This could have been fixed recently. Feel free to test.

**Comment by gregorulm** [comment]
That's great! I'll do a few test runs once #63 is fixed.

**Comment by gregorulm** [comment]
@kdex This bug seem to have been resolved.
