### ISSUE TITLE
Practice Mode: garbage lines, additional lag

### ISSUE THREAD

**Issue by gregorulm** [shiromino/shiromino#49]
Consider adding an extra practice mode with additional features:
- garbage lines (selectable number of lines of garbage -- zero to ten?; also variable difficulty, i.e. one whole per line up to really messy stacks)
- add additional lag (Shiromino is more responsive than the arcade originals, so having an option to increase lag may make it a better practice tool for the arcade originals)
- selectable seed for garbage/piece sequence (the seed is already recorded by the game and printed to the CLI, so this would be relatively straightforward to add)

**Comment by FelicityVi** [comment]
The garbage lines and selectable seed are now both covered by the improved Multi-Editor. Garbage lines aren't randomly generated but they can be drawn in the field editor, which to me is good enough.

As for adding additional lag solely for the purpose of practicing for the arcade originals, I'm not interested in implementing this feature. Shiromino is it's own thing, and though many people use it as a substitute for the TGM games, adding frames of lag to the game even as an optional thing is slightly weird and unnecessary to me.

In the far future, we may implement the lag feature as part of an "emulation mode" that attempts to be as faithful as possible to the original arcade games. But I'm closing this for the time being.
