### ISSUE TITLE
Document grading criteria of Pentomino C mode

### ISSUE THREAD

**Issue by gregorulm** [shiromino/shiromino#50]
The conditions of reaching GM in Pentomino C are not documented and should be added to the readme file. Of course, I'm assuming that this grade has been implemented (if not, it should be added because a primary reason why people play those games is to get validation from a machine).

**Comment by FelicityVi** [comment]
Thank you for the suggestion. I've now added documentation about the Pentomino C mode to a new file [`docs/MODES.md`](https://github.com/shiromino/shiromino/blob/master/doc/MODES.md).
