### ISSUE TITLE
Route CLI output to text file

### ISSUE THREAD

**Issue by gregorulm** [shiromino/shiromino#53]
Shiromino prints game results to the CLI, e.g. 

```
Random seed: 2577947617
Music: 2
First piece
Wrote replay 1934:  --  G2 DEATH    400-472   00:29:43   2020.08.06
```

Could you also write this to stdout? It would be neat to be able to run `./build/shiromino > out.txt` and get data collected automatically. This is not an overly important feature, but I find it quite neat to visualize progress by visualizing a time series of my game results. For that purpose, getting new entries as lines (CSV-style) would be particularly useful, i.e. put all information for one game on one line and separate values by commas.

Collecting seed information this way would also help with researching #47 .

**Comment by kdex** [comment]
There are a couple of related things buried in this issue:

(1) Exporting metrics: With a revised replay management (covered by #13 and #36), I'd imagine there to be a means to export replays or information about all replays from the GUI as well as from the CLI. Something along the lines of having a command-line flag like `--export-csv <path-to-database>` should probably suffice. I'd argue that it's probably enough to start with that, and maybe add filters (like `--from 2020-01-01`) later on.

(2) Visualizing progress: This could very well be its own feature in the game (see #37). 

(3) SQLite: For now, all of this information is already in the SQLite database anyway, so you might as well use it directly:

```bash
$ sqlite3 -header -csv shiromino.sqlite "SELECT mode, startlevel, level, time, date FROM scores;"
```

However, this does not address the seed. It's currently stored within the replay itself (stored as a blob in SQLite). Unfortunately, the offset is currently very much dependent on your architecture:

```c
void read_replay_from_memory(struct replay *out_replay, const uint8_t *buffer, size_t bufferLength)
{
    // Keep the same existing format
    const uint8_t *scanner = buffer;

    out_replay->mode = ((int *)scanner)[0];
    scanner += sizeof(int);

    out_replay->mode_flags = ((int *)scanner)[0];
    scanner += sizeof(int);

    out_replay->seed = ((long *)scanner)[0]; // <---- There you go
    scanner += sizeof(long);
```

While I think it could be useful to get the seed out into the `scores` table schema as well, none of the information currently on stderr is supposed to be relied on by external programs, and just redirecting it to stdout isn't really that convenient either (see (1)).

Would it be it okay for you if we merged this issue with one of the above, or if we repurposed this issue to track the `scores` schema migration instead?

**Comment by gregorulm** [comment]
Re. 1) With an added timestamp this would indeed work well. My original suggestion was that Shiromino would write to CSV, which I'd then process in a separate Python script to visualize it. Of course, by querying the database directly, this would be even faster.

Re. 2) The replay screen should only focus on the current game, I'd say. Time series of the last X games should be separate. JStris has some basic but still insightful visualizations, which could serve as inspiration. In any case, this is not really a high-priority feature but certainly one that would be nice to have. (Currently, I enter the level reached for each G2 Death game, starting from 0 and plot that. I don't bother recording times, but I would plot that if I could easily retrieve that data.)

Re. 3) I didn't run that SQL query, but my understanding is that you only save the date, not a timestamp. My use case would be to extract all results of one session in chronological order and plot it as a time series. In contrast, the ordering in the database is based on mode and then results.

Feel free to close/merge/repurpose the issues I created in whatever way that suits you best.

**Comment by kdex** [comment]
Thanks for the feedback.

As for (3), the database uses Unix timestamps in the `date` column, allowing you to extract an exact time in addition to just a date.

> In contrast, the ordering in the database is based on mode and then results.

The database itself should include the data in insertion order, so in case you're using a graphical front end for SQLite, beware that what you're seeing is not necessarily the way the data is stored in the database. You can control the ordering yourself via `ORDER BY`; so, to make sure you're getting G2 Death data in chronological order, you'd issue something along the lines of

```sql
SELECT mode, startlevel, level, time, date FROM scores WHERE mode = 256 ORDER BY date ASC;
```

Right now, `mode = 256` indicates G2 Death, which isn't really all that readable. Expect a database migration to change that at some point in the future.

For now, I'll merge this with #13.
