### ISSUE TITLE
BUTTONESCAPE is not compatible with arcade controls

### ISSUE THREAD

**Issue by ericjtaylor** [shiromino/shiromino#57]
When running shiromino on an arcade cabinet, the buttons available for input are all very easy to hit during gameplay. It's too risky to map escape to any of them.

Currently when you finish a credit the only way to start again is pressing BUTTONESCAPE. Requiring a whole keyboard just for this one button is also not the best user experience. BUTTONESCAPE can certainly stay (say for users who love restarting), but I think the user interface should be modified so that this button is not required to return to the menu.

A short 1-2 second animation clearing the playfield followed by a "press any key" prompt would serve this purpose, though I don't have any strong opinions on the design.

**Comment by kdex** [comment]
@ericjtaylor Thanks for the issue.

To reduce any potential confusion: As far as I remember, `BUTTONESCAPE` is just a virtual handle, it doesn't really need to be the Escape key on a keyboard; you could set it up to be anything, even an arcade-stick button. The naming is not perfect and may be subject to change in the next major version.

Does that help you in any way?

**Comment by ericjtaylor** [comment]
The problem is that if you hit it during gameplay you quit to menu. So mapping it to a joystick button comes with the extreme risk of prematurely ending games unintentionally.

**Comment by kdex** [comment]
@ericjtaylor Ah, gotcha; that's definitely an issue, thank you for elaborating.
