### ISSUE TITLE
Shiromino no longer starts up properly on macOS 10.15

### ISSUE THREAD

**Issue by gregorulm** [shiromino/shiromino#63]
This is the console output of the current master when starting up the application with a default `.ini` file:

```shiromino % ./build/shiromino --configuration-file ./shiromino.ini
Binding for START is invalid.
Binding for ESCAPE is invalid.
Configuration file: "./shiromino.ini"
...
Failed to init screen, aborting```

**Comment by kdex** [comment]
@nightmareci This error string appears to be new. Do you have a hunch what could be going on?

**Comment by kdex** [comment]
I have verified that current builds work as expected on macOS 10.15.5.

Please make sure that your environment supports OpenGL. Vulkan support is already on the roadmap. See #28.
