### ISSUE TITLE
Installation Issues (Not sure where else to post this)

### ISSUE THREAD

**Issue by machinegungeek** [shiromino/shiromino#65]
For reference, I am on Windows 10, using Visual Studio 2019 and the appropriate instructions for that set-up, and shiromino version 0.1.0.

Issue 1:
Running 
```shell
$ cmake -B build -DCMAKE_TOOLCHAIN_FILE=[path to vcpkg]/scripts/buildsystems/vcpkg.cmake -S .
```
results in errors in locating the SDL files (SDL2, mixer, etc.).

Workaround 1:
Setting ```shell -DCMAKE_PREFIX_PATH=C:\src\vcpkg\installed\x64-windows``` allows the build to proceed correctly.

Issue 2:
Trying to double click run the executable results in errors in finding the various SDL dll files. (Pop-up warning messages).

Workaround 2: 
Copy and paste the .dll files from the vcpkg\installed\x64-windows\include directory to the build/Release directory.

Issue 3:
Workaround 2 allows the executable to launch. However, it just hangs on a black screen.

**Comment by kdex** [comment]
@machinegungeek

Issue 1: It looks like you forgot to replace `[path to vcpkg]`. Could that be your issue? [The readme has a section on this.](https://github.com/shiromino/shiromino#windows-visual-studio-x64-via-cmdexe-or-powershell)

Issue 2: [This is covered by our readme.](https://github.com/shiromino/shiromino#running) Basically, use the `-c` flag.

**Comment by machinegungeek** [comment]
Thanks for the quick response. I didn't realize that setting the vcpkg as an environment variable would affect as much as it does. Redoing the build with the correct path set did fix issues 1 and 2. Just copying assets to the working directory fixed issue 3 (though one could also just set the BASE_PATH in the .ini file to the root shiromino folder as well).
